version: "3.8"

services:
  go:
    build: ./projects/
    ports:
      - 80:8080
    volumes:
      - ./projects:/app
    networks:
      - mynet
    depends_on:
      - postgres
    environment:
      - PGUSER=${PGUSER:?user not set}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-postgresdb}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-sgp}
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    build: ./database
    hostname: postgresdb
    volumes:
      - ./database/init-scripts/:/initdb.d/
      - /var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    restart: always
    networks:
      - mynet
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    networks:
      - mynet

networks:
  mynet: