version: "3.8"

services:
  # go:
  #   build: ./projects
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./projects:/app
  #   networks:
  #     - database
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   env_file: .env

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - ./database/init-scripts/:/docker-entrypoint-initdb.d/
      - sgp_postgres_data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - database
    ports:
      - 5432:5432
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
    #     ]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3

  adminer:
    image: adminer:4.8.1
    ports:
      - 80:8080
    networks:
      - database

networks:
  database:
volumes:
  sgp_postgres_data:
    external: false
