#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PGUSER WITH PASSWORD $PGPASSWORD;
    CREATE DATABASE $PGDATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $PGDATABASE TO $PGUSER;
EOSQL